#ifndef GAME_SERVER_LASTDAY_DEFINE_H
#define GAME_SERVER_LASTDAY_DEFINE_H

enum LastDayWeapon
{
    TWS_WEAPON_HAMMER=0,
    TWS_WEAPON_GUN,
    TWS_WEAPON_SHOTGUN,
    TWS_WEAPON_GRENADE,
    TWS_WEAPON_RIFLE,
    TWS_WEAPON_NINJA,

    LD_WEAPON_HAMMER_PLUS,

    NUM_LD_WEAPONS,
};


#endif